---
abstract: 'turns baubles into trinkets'
author:
  - 'Aaron Johnson <aaronjjohnson@gmail.com>'
build_requires:
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Spotify
requires:
  Data::Dumper: 0
  File::Basename: 0
  HTTP::Headers: 0
  IO::CaptureOutput: 0
  JSON::Path: 0
  JSON::XS: 0
  Moose: 0
  Scalar::Util: 0
  URI: 0
  URI::Escape: 0
  WWW::Mechanize: 0
  XML::Simple: 0
  strict: 0
  warnings: 0
version: 0.001
